### ISSUE TITLE
Review for assignment 3

### ISSUE THREAD

**Issue by sriram-srinivasan** [mgkanani/raft#2]
This is a review for assignment 3. 
1. I loved the fact that you tested on multiple machines and attempted to induce all kinds of faults. Good job. 
2. Back to basics though. By "testing should be automated", I mean "automatic verification". It is one thing to induce faults, but equally important to _verify_ automatically whether the code is running as expected; that means doing something with the testing.T parameter in TestRaft(). This is usually tougher than the code being tested. 
3. Servers and testing should always run silent. Logging should be done under an if-clause, and turned on only when debugging or monitoring something specific.
4. raft.Start() -- A service should start on its own; it shouldn't require prodding from a test or some external bit of code to start. 
5. In Start(), a more compact replacement for the if-then-else- logic is 
   
   ```
   switch serve.ServState.my_state {
     case follower: ...
     case leader: ...
     case candidate: ...
   }
   ```
   
   I'm using consts follower, leader, candidate instead of 0, 1, 2
6. I'm not sure if splitting ServState into a separate struct buys you much. Also, what is the purpose of RaftType?
7. isLeader(). A more compact version is `return raft.Leader > 0`. 
8. Is the time.Sleep() at line 180 a hook for the test framework to induce faults? If so, the name of the channel should be more appropriate; not 'ch'.

**Comment by mgkanani** [comment]
sir,
    I am making main program to write their current term and leader for that term(means to whom they have voted) in file `raft_servers.log` during their execution. In testing, 
->first start all servers 
->killing one server and waiting for 5-sec then restarting it 
->and then kill other servers. 

this killing and restarting is done 3 times.

each server is writing it's term and leader at every 3.1sec.

e.g. 
`[ 3 ] Current Term is :- 1 Current Leader is:- 1`
3 is server-id , term corresponding to server-3 is 1 and it has voted to server-1.

if there is no leader, in candidate-state then it will return `-1`.

Now, What should i do? whether should i write more testing procedures or go for assignment#4?
should i use rpc or is this fine?

Thank you.

**Comment by sriram-srinivasan** [comment]
At this point, you are in good shape to go for assignment 4.  You'll be fiddling with the state machine anyway.
